include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Generated code
    - 'lib/**.config.dart'
    - 'lib/**.g.dart'
    - 'lib/**.freezed.dart'
    - 'lib/**.graphql.dart'
    - 'lib/**.gen.dart'
    - 'lib/generated_plugin_registrant.dart'
    - 'lib/pigeon.dart'
    # Web
    - 'web/**'
    # Build
    - 'build/**'
    # Assets
    - 'assets/**'

linter:
  rules:
